-- Permite a cualquier usuario activo con acceso a Auditoria retirar un codigo
-- todavia no contado de una sesion abierta. La operacion es atomica y deja
-- trazabilidad aun despues de eliminar la asignacion original.

create table if not exists public.audit_session_item_removal_log (
  id bigint generated by default as identity primary key,
  item_id uuid not null,
  session_id uuid not null references public.audit_sessions(id) on delete cascade,
  product_id uuid not null,
  sku_snapshot text,
  description_snapshot text,
  source text not null,
  system_stock_snapshot numeric not null default 0,
  cost_snapshot numeric not null default 0,
  removed_by uuid not null references public.cyclic_users(id),
  removed_by_name text,
  removed_at timestamptz not null default now()
);

create index if not exists idx_audit_item_removal_log_session_time
  on public.audit_session_item_removal_log(session_id, removed_at desc);

create index if not exists idx_audit_item_removal_log_actor_time
  on public.audit_session_item_removal_log(removed_by, removed_at desc);

create or replace function public.remove_audit_session_item(
  p_item_id uuid,
  p_actor_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor public.cyclic_users%rowtype;
  v_item public.audit_session_items%rowtype;
  v_session public.audit_sessions%rowtype;
  v_sku text;
  v_description text;
begin
  select * into v_actor
  from public.cyclic_users
  where id = p_actor_id and is_active = true;

  if not found then
    return jsonb_build_object('ok', false, 'message', 'Usuario inactivo o no encontrado.');
  end if;

  if not (
    v_actor.role in ('Administrador', 'Validador', 'Supervisor')
    or coalesce(v_actor.can_access_audit, false)
    or coalesce(v_actor.module_access, '[]'::jsonb) ? 'audit'
  ) then
    return jsonb_build_object('ok', false, 'message', 'El usuario no tiene acceso al modulo de Auditoria.');
  end if;

  select * into v_item
  from public.audit_session_items
  where id = p_item_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'message', 'El producto ya no esta asignado a la sesion.');
  end if;

  select * into v_session
  from public.audit_sessions
  where id = v_item.session_id;

  if not found or v_session.status <> 'in_progress' then
    return jsonb_build_object('ok', false, 'message', 'Solo se pueden quitar productos de una sesion en progreso.');
  end if;

  if not coalesce(v_actor.can_access_all_stores, false)
     and v_actor.store_id is distinct from v_session.store_id then
    return jsonb_build_object('ok', false, 'message', 'El usuario no tiene acceso a la tienda de esta sesion.');
  end if;

  if v_item.source <> 'selected' then
    return jsonb_build_object('ok', false, 'message', 'Solo se pueden quitar productos de la lista asignada.');
  end if;

  if exists (
    select 1 from public.audit_counts c
    where c.item_id = v_item.id
    limit 1
  ) then
    return jsonb_build_object('ok', false, 'message', 'El producto ya tiene registros y no se puede quitar.');
  end if;

  select p.sku, p.description
    into v_sku, v_description
  from public.cyclic_products p
  where p.id = v_item.product_id;

  insert into public.audit_session_item_removal_log (
    item_id, session_id, product_id, sku_snapshot, description_snapshot,
    source, system_stock_snapshot, cost_snapshot, removed_by, removed_by_name
  ) values (
    v_item.id, v_item.session_id, v_item.product_id, v_sku, v_description,
    v_item.source, coalesce(v_item.system_stock, 0), coalesce(v_item.cost_snapshot, 0),
    v_actor.id, v_actor.full_name
  );

  delete from public.audit_session_items
  where id = v_item.id;

  return jsonb_build_object('ok', true, 'message', 'Producto quitado de la sesion.');
end;
$$;

revoke all on function public.remove_audit_session_item(uuid, uuid) from public;
grant execute on function public.remove_audit_session_item(uuid, uuid) to anon, authenticated;

